import type { Metadata } from 'next'
export const revalidate = 3600

import { HubShell } from '@/components/hub/hub-shell'
import { operators } from '@/config/operators'
import type { Locale } from '@/i18n/routing'
import { buildHreflang } from '@/lib/i18n/routes'

export async function generateMetadata({
  params,
}: {
  params: Promise<{ locale: Locale }>
}): Promise<Metadata> {
  const { locale } = await params
  const isFr = locale === 'fr'
  return {
    title: isFr
      ? 'Meilleur Casino Mobile 2026 France — iOS Android testé'
      : 'Best Mobile Casino 2026 France — iOS Android tested',
    description: isFr
      ? 'Les meilleurs casinos mobile en France 2026 : iOS, Android, PWA testés sur iPhone et Samsung Galaxy. Interface, rapidité et jeux disponibles comparés. 18+'
      : 'Best mobile casinos in France 2026: iOS, Android, PWA tested on iPhone and Samsung Galaxy. Interface, speed and available games compared. 18+',
    alternates: { languages: buildHreflang('/casinos/mobile/') },
  }
}

const FAQ_FR = [
  {
    question: 'Faut-il télécharger une application pour jouer en casino mobile ?',
    answer:
      "Non, la plupart des casinos mobiles fonctionnent directement via le navigateur (Chrome, Safari) sans téléchargement. C'est le format le plus courant. Certains casinos proposent en complément une application iOS (via l'App Store) ou Android (via APK à télécharger directement, car les casinos ne peuvent pas figurer sur le Play Store). L'application offre généralement de meilleures performances et des notifications push.",
  },
  {
    question: 'Les jeux sont-ils différents sur mobile et sur ordinateur ?',
    answer:
      "Non, les jeux sont identiques. Les éditeurs comme NetEnt, Pragmatic et Play'n GO développent en HTML5 responsive — le même jeu s'adapte automatiquement à l'écran. Les RTP sont identiques, les résultats sont générés par le même RNG. La seule différence notable : certains jeux avec des interfaces complexes (bonus games interactifs) peuvent être plus difficiles à manier sur petit écran.",
  },
  {
    question: "Un casino mobile peut-il m'être extorquer via des achats in-app ?",
    answer:
      "Non. Les casinos en argent réel n'utilisent pas de mécaniques d'achats in-app. Vous déposez de l'argent via la caisse (section Paiements), vous jouez, et vous retirez vos gains. Il n'y a pas d'achats cachés. Méfiez-vous des applications de \"casino social\" gratuites qui, elles, utilisent des achats in-app — elles n'ont rien à voir avec les casinos en argent réel.",
  },
  {
    question: 'La connexion 4G est-elle suffisante pour jouer en casino live mobile ?',
    answer:
      "Oui, une 4G stable à partir de 10 Mb/s est suffisante pour le casino live en HD. Sur 5G, l'expérience est identique au WiFi. Les problèmes surviennent généralement avec une 4G instable en déplacement (train, zones de faible couverture) — dans ce cas, la vidéo peut se pixeliser ou la connexion peut être coupée. Pour le casino live, privilégiez une connexion WiFi ou 5G stable.",
  },
  {
    question: 'Comment sécuriser son compte casino sur mobile ?',
    answer:
      "Activez l'authentification à deux facteurs (2FA) si disponible. Utilisez un mot de passe unique et fort. Ne stockez jamais votre mot de passe dans le navigateur mobile si d'autres personnes utilisent votre téléphone. Activez le verrouillage biométrique (Face ID, empreinte) sur l'application casino si disponible. Déconnectez-vous après chaque session sur un appareil partagé.",
  },
  {
    question: 'Les bonus sont-ils les mêmes sur mobile et desktop ?',
    answer:
      "Oui, les bonus sont identiques quel que soit l'appareil. Certains casinos proposent en revanche des \"bonus mobiles\" exclusifs pour les joueurs qui s'inscrivent ou déposent depuis l'application — généralement des tours gratuits supplémentaires. Ces offres sont ponctuelles et figurent dans la section Promotions de l'application.",
  },
]

const FAQ_EN = [
  {
    question: 'Do you need to download an app to play at a mobile casino?',
    answer:
      'No, most mobile casinos work directly via browser (Chrome, Safari) without downloading. This is the most common format. Some casinos also offer an iOS app (via the App Store) or Android (via APK downloaded directly, as casinos cannot appear on the Play Store). The app generally offers better performance and push notifications.',
  },
  {
    question: 'Are games different on mobile and desktop?',
    answer:
      "No, the games are identical. Publishers like NetEnt, Pragmatic and Play'n GO develop in responsive HTML5 — the same game automatically adapts to the screen. RTPs are identical, results are generated by the same RNG. The only notable difference: some games with complex interfaces (interactive bonus games) may be harder to handle on a small screen.",
  },
  {
    question: 'Can a mobile casino charge me through in-app purchases?',
    answer:
      "No. Real-money casinos do not use in-app purchase mechanics. You deposit money via the cashier (Payments section), you play, and you withdraw your winnings. There are no hidden purchases. Beware of free 'social casino' apps which do use in-app purchases — they have nothing to do with real-money casinos.",
  },
  {
    question: 'Is a 4G connection sufficient to play live casino on mobile?',
    answer:
      'Yes, a stable 4G connection from 10 Mb/s is sufficient for HD live casino. On 5G, the experience is identical to WiFi. Problems generally occur with unstable 4G while moving (train, low coverage areas) — in that case, video may pixelate or the connection may be cut. For live casino, prefer a stable WiFi or 5G connection.',
  },
  {
    question: 'How do you secure your casino account on mobile?',
    answer:
      'Enable two-factor authentication (2FA) if available. Use a unique and strong password. Never store your password in the mobile browser if other people use your phone. Enable biometric locking (Face ID, fingerprint) on the casino app if available. Log out after each session on a shared device.',
  },
  {
    question: 'Are bonuses the same on mobile and desktop?',
    answer:
      "Yes, bonuses are identical regardless of device. Some casinos offer exclusive 'mobile bonuses' for players who register or deposit via the app — usually extra free spins. These offers are periodic and appear in the app's Promotions section.",
  },
]

export default async function CasinosMobilePage({
  params,
}: {
  params: Promise<{ locale: Locale }>
}) {
  const { locale } = await params
  const isFr = locale === 'fr'

  const mobileCasinos = [...operators].sort((a, b) => {
    const aMobile = a.features.some((f) => /mobile|app|pwa|ios|android/i.test(f)) ? 2 : 0
    const bMobile = b.features.some((f) => /mobile|app|pwa|ios|android/i.test(f)) ? 2 : 0
    return bMobile - aMobile || b.rating - a.rating
  })

  const BASE_URL =
    process.env['NEXT_PUBLIC_SITE_URL'] ?? 'https://www.le-meilleur-casino-en-ligne.fr'
  const schemaItemList = {
    '@context': 'https://schema.org',
    '@type': 'ItemList',
    name: isFr ? 'Meilleurs casinos mobile France 2026' : 'Best Mobile Casinos France 2026',
    itemListElement: mobileCasinos.slice(0, 10).map((op, i) => ({
      '@type': 'ListItem',
      position: i + 1,
      name: op.name,
      url: `${BASE_URL}${isFr ? '' : '/en'}/casinos/${op.slug}/`,
    })),
  }
  const schemaFAQ = {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: (isFr ? FAQ_FR : FAQ_EN).map((q) => ({
      '@type': 'Question',
      name: q.question,
      acceptedAnswer: { '@type': 'Answer', text: q.answer },
    })),
  }

  return (
    <HubShell
      pageType="casino_mobile"
      locale={locale}
      breadcrumbItems={[
        { label: isFr ? 'Accueil' : 'Home', href: '/' },
        { label: isFr ? 'Casinos en ligne' : 'Online Casinos', href: '/casinos/' },
        { label: isFr ? 'Casino Mobile' : 'Mobile Casino' },
      ]}
      eyebrow={
        isFr
          ? 'iOS · Android · PWA · Testé sur mobile · 2026'
          : 'iOS · Android · PWA · Mobile tested · 2026'
      }
      heading={
        isFr ? (
          <>
            Meilleur <em className="not-italic text-green">casino mobile</em> 2026
          </>
        ) : (
          <>
            Best <em className="not-italic text-green">mobile casino</em> 2026
          </>
        )
      }
      intro={
        isFr
          ? 'Classement des casinos testés sur iPhone et Android. Interface tactile, rapidité de chargement et disponibilité des jeux sur smartphone — les vrais critères du mobile.'
          : 'Casinos ranked and tested on iPhone and Android. Touch interface, loading speed and game availability on smartphone.'
      }
      schemaItemList={schemaItemList}
      schemaFAQ={schemaFAQ}
      operators={mobileCasinos}
      configKey="mobile"
      editorialH2={
        isFr ? "L'expérience casino sur mobile en 2026" : 'The casino mobile experience in 2026'
      }
      editorialContent={
        isFr ? (
          <div className="space-y-4 text-[15.5px] leading-[1.7] text-ink-2">
            <p>
              Plus de 60% des joueurs de casino en ligne utilisent principalement leur smartphone.
              Cette réalité a transformé l&apos;industrie : les développeurs de jeux (NetEnt,
              Pragmatic, Play&apos;n GO) conçoivent désormais leurs titres mobile-first, avec des
              interfaces adaptées aux écrans 6 pouces et aux sessions courtes. Les machines à sous
              HTML5 modernes sont aussi performantes sur mobile que sur desktop.
            </p>
            <p>
              Notre équipe teste chaque casino sur iPhone 15 Pro (iOS 17) et Samsung Galaxy S24
              (Android 14) via Chrome et Safari. Nous mesurons le{' '}
              <strong className="text-ink">temps de chargement</strong> (objectif : moins de 3
              secondes sur 4G), la fluidité des animations, la facilité d&apos;accès à la caisse, et
              la qualité du casino live mobile. Les casinos dont les boutons sont trop petits pour
              une utilisation tactile confortable sont pénalisés.
            </p>
            <p>
              LeoVegas mérite son surnom de &quot;roi du mobile&quot; : leur application iOS est
              native, rapide, et intègre toutes les fonctionnalités desktop. Betsson et 888 Casino
              ont également des applications iOS solides. Pour Android, la plupart des casinos
              proposent des APK à télécharger directement, ce qui nécessite d&apos;activer
              &quot;Sources inconnues&quot; dans les paramètres Android.
            </p>
          </div>
        ) : (
          <div className="space-y-4 text-[15.5px] leading-[1.7] text-ink-2">
            <p>
              Over 60% of online casino players use their smartphone as their primary device. This
              reality has transformed the industry: game developers (NetEnt, Pragmatic, Play&apos;n
              GO) now design their titles mobile-first, with interfaces adapted to 6-inch screens
              and short sessions. Modern HTML5 slot machines perform as well on mobile as on
              desktop.
            </p>
            <p>
              Our team tests each casino on iPhone 15 Pro (iOS 17) and Samsung Galaxy S24 (Android
              14) via Chrome and Safari. We measure{' '}
              <strong className="text-ink">loading time</strong> (target: under 3 seconds on 4G),
              animation smoothness, ease of access to the cashier, and live casino quality on
              mobile. Casinos whose buttons are too small for comfortable touch use are penalised.
            </p>
            <p>
              LeoVegas earns its nickname &apos;king of mobile&apos;: their iOS app is native, fast,
              and incorporates all desktop features. Betsson and 888 Casino also have solid iOS
              apps. For Android, most casinos offer APK files to download directly — which requires
              enabling &apos;Unknown sources&apos; in Android settings.
            </p>
          </div>
        )
      }
      faqH2={isFr ? 'Questions fréquentes — Casino Mobile' : 'FAQ — Mobile Casino'}
      faqItems={isFr ? FAQ_FR : FAQ_EN}
    />
  )
}
