// Operator seed data — source of truth for all pages.
// affiliateUrl goes through /go/[slug]/ which fires GA4 before redirecting.

export interface Operator {
  id: string
  slug: string
  name: string
  shortName?: string
  logoUrl?: string // Set when real SVG assets are available
  licence: string
  rating: number // out of 10, one decimal
  ratingLabel: 'Excellent' | 'Très bien' | 'Bien' | 'Correct'
  bonusAmount: string // display e.g. "200 €"
  bonusSuffix?: string // e.g. "+ 100 tours"
  bonusConditions: string
  bonusAmountNumber: number // for sorting
  bonusSlug: string // for GA4 data-bonus e.g. "200_euros"
  rtp: number // e.g. 96.4
  paymentMethods: string[] // display abbreviations
  features: string[]
  pros: string[]
  cons: string[]
  verdict: string
  tagline: string // one-liner for podium card
  affiliateUrl: string // real external URL (placeholder for dev)
}

// Real registration URLs per operator.
// Replace with affiliate tracking URLs once programmes are approved.
export const AFFILIATE_URLS: Record<string, string> = {
  cresus: 'https://cresuscasino-fr.net/fr/register',
  lucky8: 'https://lucky8fr.fr/fr-fr/register',
  'wild-sultan': 'https://www.wildsultan.com/fr/register',
  madnix: 'https://www.madnix.com/fr/register',
  'magical-spin': 'https://www.magicalspin.com/fr/register',
  casinozer: 'https://casinozer.com/fr/register',
  tortuga: 'https://www.tortuga.bet/fr/register',
  'banzai-slots': 'https://www.banzaislots.com/fr/register',
  stake: 'https://stake.com/fr/registration',
  'bitcoin-penguin': 'https://bitcoinpenguin.org/register',
  dublinbet: 'https://www.dublinbet.com/fr/register',
  vegadream: 'https://vegadream.com/fr/register',
  'horus-casino': 'https://www.horuscasino.com/fr/register',
  'n1-casino': 'https://www.n1casino.com/fr/welcome-page',
  'casino-extra': 'https://casinoextra-fr.fr/fr-fr/register',
  // ── New operators ────────────────────────────────────────────────────────────
  leovegas: 'https://www.leovegas.com/fr/register',
  '888-casino': 'https://www.888casino.com/fr/register',
  casumo: 'https://www.casumo.com/fr/register',
  'mr-green': 'https://www.mrgreen.com/fr/register',
  netbet: 'https://www.netbet.com/fr/register',
  playamo: 'https://www.playamo.com/fr/registration',
  'national-casino': 'https://nationalcasino.com/fr/register',
  bitstarz: 'https://www.bitstarz.com/fr/register',
  'bob-casino': 'https://www.bobcasino.com/fr/register',
  'vulkan-vegas': 'https://vulkanvegas.com/fr/register',
  vavada: 'https://vavada.com/fr/register',
  betsson: 'https://www.betsson.com/fr/register',
  'sol-casino': 'https://solcasino.io/fr/register',
  'jet-casino': 'https://jetcasino.com/fr/register',
  'fresh-casino': 'https://freshcasino.com/fr/register',
  'rox-casino': 'https://roxcasino.com/fr/register',
  'izzi-casino': 'https://izzicasino.com/fr/register',
  'joo-casino': 'https://joocasino.com/fr/register',
  'slot-hunter': 'https://slothunter.com/fr/register',
  'fight-club-casino': 'https://fightclub.casino/fr/register',
  n1bet: 'https://www.n1bet.com/fr/register',
  'bizzo-casino': 'https://bizzo-casino.com/fr/register',
  'slots-palace': 'https://slotspalace.com/fr/register',
  neon54: 'https://neon54.com/fr/register',
  posido: 'https://posido.com/fr/register',
  mystake: 'https://mystake.io/fr/register',
  'bc-game': 'https://bc.game/fr/register',
  fortunejack: 'https://fortunejack.com/fr/register',
  rollbit: 'https://rollbit.com/fr/register',
  '22bet': 'https://22bet.com/fr/register',
  lucky31: 'https://www.lucky31.com/fr/register',
  'la-riviera': 'https://www.larivieracasino.com/fr/register',
  'unique-casino': 'https://www.unique-casino.com/fr/register',
  cbet: 'https://www.cbet.gg/fr/register',
  goldenbet: 'https://goldenbet.com/fr/register',
  'pin-up': 'https://pin-up.casino/fr/register',
  parimatch: 'https://parimatch.com/fr/register',
  megapari: 'https://megapari.com/fr/register',
  'gg-bet': 'https://gg.bet/fr/register',
  rocketplay: 'https://rocketplay.io/fr/register',
  casombie: 'https://casombie.com/fr/register',
  'oshi-casino': 'https://oshi.io/fr/register',
  'mr-bit': 'https://mrbit.com/fr/register',
  nomad: 'https://nomadbet.com/fr/register',
  casinoly: 'https://casinoly.com/fr/register',
}

const LOGO_URLS: Record<string, string> = {
  cresus: '/logos/cresus.png',
  lucky8: '/logos/lucky8.png',
  'wild-sultan': '/logos/wild-sultan.png',
  madnix: '/logos/madnix.png',
  'magical-spin': '/logos/magical-spin.png',
  casinozer: '/logos/casinozer.png',
  tortuga: '/logos/tortuga.png',
  'banzai-slots': '/logos/banzai-slots.svg',
  stake: '/logos/stake.png',
  'bitcoin-penguin': '/logos/bitcoin-penguin.png',
  dublinbet: '/logos/dublinbet.png',
  vegadream: '/logos/vegadream.png',
  'horus-casino': '/logos/horus-casino.png',
  'n1-casino': '/logos/n1-casino.png',
  'casino-extra': '/logos/casino-extra.png',
  leovegas: '/logos/leovegas.png',
  '888-casino': '/logos/888-casino.png',
  casumo: '/logos/casumo.png',
  'mr-green': '/logos/mr-green.png',
  netbet: '/logos/netbet.png',
  playamo: '/logos/playamo.png',
  'bob-casino': '/logos/bob-casino.png',
  'bizzo-casino': '/logos/bizzo-casino.png',
  bitstarz: '/logos/bitstarz.png',
  'national-casino': '/logos/national-casino.png',
  'vulkan-vegas': '/logos/vulkan-vegas.png',
  vavada: '/logos/vavada.png',
  betsson: '/logos/betsson.png',
  'sol-casino': '/logos/sol-casino.png',
  'jet-casino': '/logos/jet-casino.png',
  'fresh-casino': '/logos/fresh-casino.png',
  'rox-casino': '/logos/rox-casino.png',
  'izzi-casino': '/logos/izzi-casino.png',
  'joo-casino': '/logos/joo-casino.png',
  'slot-hunter': '/logos/slot-hunter.png',
  'fight-club-casino': '/logos/fight-club-casino.png',
  n1bet: '/logos/n1bet.png',
  'slots-palace': '/logos/slots-palace.png',
  neon54: '/logos/neon54.png',
  posido: '/logos/posido.png',
  mystake: '/logos/mystake.png',
  'bc-game': '/logos/bc-game.png',
  fortunejack: '/logos/fortunejack.png',
  rollbit: '/logos/rollbit.png',
  '22bet': '/logos/22bet.png',
  lucky31: '/logos/lucky31.png',
  'la-riviera': '/logos/la-riviera.png',
  'unique-casino': '/logos/unique-casino.png',
  cbet: '/logos/cbet.png',
  goldenbet: '/logos/goldenbet.png',
  'pin-up': '/logos/pin-up.png',
  parimatch: '/logos/parimatch.png',
  megapari: '/logos/megapari.png',
  'gg-bet': '/logos/gg-bet.png',
  rocketplay: '/logos/rocketplay.png',
  casombie: '/logos/casombie.png',
  'oshi-casino': '/logos/oshi-casino.png',
  'mr-bit': '/logos/mr-bit.png',
  nomad: '/logos/nomad.png',
  casinoly: '/logos/casinoly.png',
}

function goUrl(slug: string) {
  return `/go/${slug}/`
}

export const operators: Operator[] = [
  {
    id: 'cresus',
    slug: 'cresus',
    name: 'Crésus Casino',
    shortName: 'Cresus',
    licence: 'Curaçao 8048',
    rating: 9.2,
    ratingLabel: 'Excellent',
    bonusAmount: '200 €',
    bonusSuffix: '+ 100 tours',
    bonusConditions: 'Wager 35× · dépôt min. 20 €',
    bonusAmountNumber: 200,
    bonusSlug: '200_euros',
    rtp: 96.4,
    paymentMethods: ['VISA', 'MC', '₿', 'PAYS'],
    features: ['Retrait 24h', '2 100+ jeux', 'Support FR'],
    pros: [
      'Meilleur rapport bonus/conditions du marché FR',
      'Retrait en moins de 24h',
      'Support en français 7j/7',
      'Plus de 2 100 jeux',
    ],
    cons: [
      'Interface vieillissante',
      'Pas de cashback hebdomadaire',
      'Limite de mise un peu restrictive',
    ],
    verdict:
      'Cresus est notre n°1 pour le marché français : meilleur équilibre bonus généreux, retraits rapides et service client francophone.',
    tagline: 'Le meilleur équilibre ludothèque / retraits rapides pour le marché français.',
    logoUrl: LOGO_URLS['cresus'],
    affiliateUrl: goUrl('cresus'),
  },
  {
    id: 'lucky8',
    slug: 'lucky8',
    name: 'Lucky8',
    licence: 'Curaçao',
    rating: 8.9,
    ratingLabel: 'Excellent',
    bonusAmount: '100 €',
    bonusSuffix: '+ 100 tours',
    bonusConditions: 'Wager 35× · sans code promo',
    bonusAmountNumber: 100,
    bonusSlug: '100_euros',
    rtp: 96.1,
    paymentMethods: ['VISA', 'MC', 'PAYS'],
    features: ['Tournois slots', 'Cashback hebdo', '1 800+ jeux'],
    pros: [
      'Tournois de machines à sous réguliers',
      'Cashback hebdomadaire 10%',
      'Bonus sans code promo',
    ],
    cons: [
      'Pas de support téléphonique',
      'Processus de vérification long',
      'Limite de retrait journalière',
    ],
    verdict:
      'Lucky8 se distingue par ses tournois et son cashback hebdomadaire, idéal pour les joueurs réguliers de slots.',
    tagline: 'Tournois de machines à sous et cashback hebdomadaire généreux.',
    logoUrl: LOGO_URLS['lucky8'],
    affiliateUrl: goUrl('lucky8'),
  },
  {
    id: 'wild-sultan',
    slug: 'wild-sultan',
    name: 'Wild Sultan',
    licence: 'Curaçao',
    rating: 8.7,
    ratingLabel: 'Excellent',
    bonusAmount: '500 €',
    bonusSuffix: '+ 20 tours',
    bonusConditions: 'Wager 30× · dépôt min. 20 €',
    bonusAmountNumber: 500,
    bonusSlug: '500_euros',
    rtp: 96.0,
    paymentMethods: ['VISA', '₿', 'ETH'],
    features: ['Crypto instantané', 'Live premium', '1 500+ jeux'],
    pros: [
      'Retraits crypto instantanés',
      'Sélection de tables live premium',
      'Wager parmi les plus bas du marché',
    ],
    cons: [
      'Peu de méthodes de paiement classiques',
      'Interface en anglais principalement',
      'Support parfois lent',
    ],
    verdict:
      'Wild Sultan est le choix idéal pour les joueurs crypto qui veulent des retraits immédiats et une expérience live haut de gamme.',
    tagline: 'Le spécialiste des retraits crypto instantanés et du live game premium.',
    logoUrl: LOGO_URLS['wild-sultan'],
    affiliateUrl: goUrl('wild-sultan'),
  },
  {
    id: 'madnix',
    slug: 'madnix',
    name: 'Madnix',
    licence: 'Curaçao',
    rating: 8.5,
    ratingLabel: 'Très bien',
    bonusAmount: '300 €',
    bonusSuffix: '+ 100 tours',
    bonusConditions: 'Wager 40× · dépôt min. 20 €',
    bonusAmountNumber: 300,
    bonusSlug: '300_euros',
    rtp: 95.8,
    paymentMethods: ['VISA', 'MC', '₿'],
    features: ['Design immersif', 'Missions quotidiennes', '3 000+ jeux'],
    pros: [
      'Plus de 3 000 jeux disponibles',
      'Programme de fidélité avec missions',
      'Design soigné et immersif',
    ],
    cons: [
      'Conditions de bonus élevées (40×)',
      'Support moins réactif la nuit',
      'Pas de Paysafecard',
    ],
    verdict:
      'Madnix offre la plus grande ludothèque de notre comparatif, idéale pour les joueurs qui veulent de la variété.',
    tagline: 'La plus grande ludothèque et des missions de fidélité qui récompensent vraiment.',
    logoUrl: LOGO_URLS['madnix'],
    affiliateUrl: goUrl('madnix'),
  },
  {
    id: 'magical-spin',
    slug: 'magical-spin',
    name: 'Magical Spin',
    licence: 'Curaçao',
    rating: 8.3,
    ratingLabel: 'Très bien',
    bonusAmount: '1 000 €',
    bonusSuffix: '+ 100 tours',
    bonusConditions: 'Wager 35× · 4 premiers dépôts',
    bonusAmountNumber: 1000,
    bonusSlug: '1000_euros',
    rtp: 95.6,
    paymentMethods: ['VISA', 'MC', 'PAYS'],
    features: ['Bonus 4 dépôts', 'VIP dédié FR', '2 000+ jeux'],
    pros: [
      'Le plus gros package de bienvenue (1 000 €)',
      'Gestionnaire VIP dédié',
      'Excellent service francophone',
    ],
    cons: ['Bonus réparti sur 4 dépôts', 'Interface moins moderne', 'Retraits en 48-72h'],
    verdict:
      'Magical Spin propose le package de bienvenue le plus généreux en valeur absolue, avec un accompagnement VIP de qualité.',
    tagline: 'Le plus gros bonus de bienvenue du marché et un suivi VIP personnalisé.',
    logoUrl: LOGO_URLS['magical-spin'],
    affiliateUrl: goUrl('magical-spin'),
  },
  {
    id: 'casinozer',
    slug: 'casinozer',
    name: 'Casinozer',
    licence: 'Curaçao',
    rating: 8.1,
    ratingLabel: 'Très bien',
    bonusAmount: '450 €',
    bonusSuffix: '+ 270 tours',
    bonusConditions: 'Wager 35× · 3 premiers dépôts',
    bonusAmountNumber: 450,
    bonusSlug: '450_euros',
    rtp: 95.4,
    paymentMethods: ['VISA', '₿', 'PAYS'],
    features: ['270 tours offerts', 'Cashback 10%', '2 500+ jeux'],
    pros: [
      'Nombre de tours gratuits exceptionnel (270)',
      'Cashback 10% sur les pertes',
      'Bonne sélection crypto',
    ],
    cons: [
      'Interface parfois surchargée',
      'Processus KYC strict',
      'Support disponible uniquement en chat',
    ],
    verdict:
      'Casinozer est le meilleur choix si vous recherchez un grand nombre de tours gratuits et un cashback hebdomadaire.',
    tagline: '270 tours gratuits et cashback hebdomadaire — le meilleur rapport tours/bonus.',
    logoUrl: LOGO_URLS['casinozer'],
    affiliateUrl: goUrl('casinozer'),
  },
  {
    id: 'tortuga',
    slug: 'tortuga',
    name: 'Tortuga Casino',
    shortName: 'Tortuga',
    licence: 'Curaçao',
    rating: 7.9,
    ratingLabel: 'Bien',
    bonusAmount: '750 €',
    bonusSuffix: '+ 30 tours',
    bonusConditions: 'Wager 30× · dépôt min. 20 €',
    bonusAmountNumber: 750,
    bonusSlug: '750_euros',
    rtp: 95.2,
    paymentMethods: ['VISA', 'MC'],
    features: ['Wager bas (30×)', 'Thème aventure', '1 200+ jeux'],
    pros: [
      'Conditions de mise parmi les plus basses (30×)',
      'Bonus sur plusieurs dépôts',
      'Thème original et engageant',
    ],
    cons: [
      'Peu de méthodes de paiement',
      'Moins de jeux que la concurrence',
      'Support par e-mail uniquement',
    ],
    verdict:
      'Tortuga se distingue par ses conditions de wager basses, idéal pour les joueurs qui veulent réellement récupérer leurs bonus.',
    tagline: 'Le wager le plus bas du top 10 — les conditions les plus honnêtes du marché.',
    logoUrl: LOGO_URLS['tortuga'],
    affiliateUrl: goUrl('tortuga'),
  },
  {
    id: 'banzai-slots',
    slug: 'banzai-slots',
    name: 'Banzai Slots',
    licence: 'Curaçao',
    rating: 7.7,
    ratingLabel: 'Bien',
    bonusAmount: '250 €',
    bonusSuffix: '+ 50 tours',
    bonusConditions: 'Wager 40× · dépôt min. 15 €',
    bonusAmountNumber: 250,
    bonusSlug: '250_euros',
    rtp: 95.0,
    paymentMethods: ['VISA', 'MC', 'SKRL'],
    features: ['Slots exclusifs', 'Tournois quotidiens', '1 600+ jeux'],
    pros: [
      'Tournois slots quotidiens avec cagnotte',
      'Slots exclusifs introuvables ailleurs',
      'Dépôt minimum faible (15 €)',
    ],
    cons: ['Wager élevé (40×)', 'Pas de crypto', 'Live casino limité'],
    verdict:
      'Banzai Slots est le paradis des fans de machines à sous avec ses tournois quotidiens et ses exclusivités.',
    tagline: 'Tournois slots quotidiens et jeux exclusifs pour les amateurs de machines à sous.',
    logoUrl: LOGO_URLS['banzai-slots'],
    affiliateUrl: goUrl('banzai-slots'),
  },
  {
    id: 'stake',
    slug: 'stake',
    name: 'Stake Casino',
    shortName: 'Stake',
    licence: 'Curaçao 8048',
    rating: 7.5,
    ratingLabel: 'Bien',
    bonusAmount: '200 €',
    bonusSuffix: '',
    bonusConditions: 'Wager 40× · sur invitation VIP',
    bonusAmountNumber: 200,
    bonusSlug: '200_euros',
    rtp: 97.0,
    paymentMethods: ['₿', 'ETH', 'LTC', 'DOGE'],
    features: ['100% crypto', 'RTP 97%', 'Jeux maison'],
    pros: [
      'RTP exceptionnel grâce aux jeux maison (97%)+ ',
      '100% crypto, retrait immédiat',
      'Jeux originaux uniques',
    ],
    cons: [
      'Pas de méthodes de paiement classiques',
      'Bonus réservé aux VIP invités',
      'Interface technique, peu intuitive',
    ],
    verdict:
      'Stake est le meilleur casino crypto du marché avec des RTP imbattables sur ses jeux exclusifs.',
    tagline: 'Le leader mondial du casino crypto avec des RTP imbattables.',
    logoUrl: LOGO_URLS['stake'],
    affiliateUrl: goUrl('stake'),
  },
  {
    id: 'bitcoin-penguin',
    slug: 'bitcoin-penguin',
    name: 'BitcoinPenguin',
    licence: 'Curaçao',
    rating: 7.3,
    ratingLabel: 'Bien',
    bonusAmount: '150 €',
    bonusSuffix: '+ 75 tours',
    bonusConditions: 'Wager 50× · BTC uniquement',
    bonusAmountNumber: 150,
    bonusSlug: '150_euros',
    rtp: 96.8,
    paymentMethods: ['₿', 'LTC', 'ETH', 'DOGE'],
    features: ['BTC & altcoins', 'Anonyme', '1 000+ jeux'],
    pros: ['Accepte de nombreuses cryptomonnaies', 'Jeu anonyme possible', 'RTP élevé (96.8%)'],
    cons: ['Wager très élevé (50×)', 'Pas de monnaies fiat', 'Support limité en FR'],
    verdict:
      "BitcoinPenguin est idéal pour les joueurs crypto qui privilégient l'anonymat et acceptent des conditions de bonus plus strictes.",
    tagline: "Anonymat crypto garanti et large sélection d'altcoins pour les puristes.",
    logoUrl: LOGO_URLS['bitcoin-penguin'],
    affiliateUrl: goUrl('bitcoin-penguin'),
  },
  // ── Nouveaux opérateurs Phase 9 ─────────────────────────────────────────────
  {
    id: 'dublinbet',
    slug: 'dublinbet',
    name: 'Dublinbet',
    shortName: 'Dublinbet',
    licence: 'MGA (Malte)',
    rating: 7.1,
    ratingLabel: 'Bien',
    bonusAmount: '500 €',
    bonusSuffix: '+ 100 tours',
    bonusConditions: 'Wager 35× · dépôt min. 20 €',
    bonusAmountNumber: 500,
    bonusSlug: '500_euros',
    rtp: 96.5,
    paymentMethods: ['VISA', 'MC', 'SKRL', 'PAYS'],
    features: ['Licence MGA', 'Live specialist', '2 000+ jeux'],
    pros: [
      'Licence MGA — la plus protectrice du marché',
      'Spécialiste du live casino depuis 2010',
      'Retraits rapides et fiables',
    ],
    cons: [
      'Interface moins moderne que la concurrence',
      'Pas de crypto',
      'Catalogue de slots moins vaste',
    ],
    verdict:
      'Dublinbet est la référence live du marché, avec la licence MGA qui offre le niveau de protection le plus élevé pour les joueurs.',
    tagline: 'Licence MGA et live casino premium — le choix sécurité pour les joueurs exigeants.',
    logoUrl: LOGO_URLS['dublinbet'],
    affiliateUrl: goUrl('dublinbet'),
  },
  {
    id: 'vegadream',
    slug: 'vegadream',
    name: 'Vegadream',
    licence: 'Curaçao',
    rating: 6.9,
    ratingLabel: 'Bien',
    bonusAmount: '200 €',
    bonusSuffix: '+ 50 tours',
    bonusConditions: 'Wager 35× · dépôt min. 20 €',
    bonusAmountNumber: 200,
    bonusSlug: '200_euros',
    rtp: 95.9,
    paymentMethods: ['VISA', 'MC', '₿', 'PAYS'],
    features: ['Support FR 24h', 'Interface française', '1 800+ jeux'],
    pros: [
      'Support francophone 24h/24',
      'Interface entièrement en français',
      'Promotions hebdomadaires régulières',
    ],
    cons: [
      'Catalogue en dessous des leaders',
      'Retraits 48–72h par CB',
      'Plafond de retrait hebdomadaire faible',
    ],
    verdict:
      'Vegadream est le casino le mieux francisé de notre comparatif — interface, support et promotions pensés pour le marché FR.',
    tagline: 'Le casino le plus francophone du marché — support et interface 100 % FR.',
    logoUrl: LOGO_URLS['vegadream'],
    affiliateUrl: goUrl('vegadream'),
  },
  {
    id: 'horus-casino',
    slug: 'horus-casino',
    name: 'Horus Casino',
    shortName: 'Horus',
    licence: 'Curaçao',
    rating: 6.7,
    ratingLabel: 'Bien',
    bonusAmount: '300 €',
    bonusSuffix: '+ 50 tours',
    bonusConditions: 'Wager 40× · dépôt min. 20 €',
    bonusAmountNumber: 300,
    bonusSlug: '300_euros',
    rtp: 95.7,
    paymentMethods: ['VISA', '₿', 'ETH'],
    features: ['Thème égyptien', 'Jackpots progressifs', 'Crypto acceptée'],
    pros: [
      'Jackpots progressifs parmi les plus élevés du marché',
      'Crypto acceptée (BTC, ETH)',
      'Design immersif et cohérent',
    ],
    cons: [
      'Wager élevé (40×)',
      'Support français pas disponible 24h/24',
      'Peu de méthodes de paiement classiques',
    ],
    verdict:
      'Horus Casino attire les chasseurs de jackpots : sa sélection de jackpots progressifs est parmi les plus généreuses du marché.',
    tagline: 'Jackpots progressifs record et thème égyptien immersif pour les chasseurs de gains.',
    logoUrl: LOGO_URLS['horus-casino'],
    affiliateUrl: goUrl('horus-casino'),
  },
  {
    id: 'n1-casino',
    slug: 'n1-casino',
    name: 'N1 Casino',
    licence: 'MGA (Malte)',
    rating: 6.5,
    ratingLabel: 'Bien',
    bonusAmount: '200 €',
    bonusSuffix: '+ 200 tours',
    bonusConditions: 'Wager 40× · dépôt min. 20 €',
    bonusAmountNumber: 200,
    bonusSlug: '200_euros',
    rtp: 96.0,
    paymentMethods: ['VISA', 'MC', 'SKRL'],
    features: ['Licence MGA', '2 000+ jeux', 'Fondé 2017'],
    pros: [
      'Licence MGA (Malta) — confiance établie depuis 2017',
      '200 tours gratuits inclus dans le bonus',
      'Large sélection de jeux de table',
    ],
    cons: ['Interface vieillissante', 'Wager 40× — dans la fourchette haute', 'Pas de crypto'],
    verdict:
      "N1 Casino est une valeur sûre pour les joueurs qui privilégient la confiance : licence MGA et 8 ans d'activité sans incident notable.",
    tagline: "8 ans d'activité sous licence MGA — la confiance éprouvée dans le temps.",
    logoUrl: LOGO_URLS['n1-casino'],
    affiliateUrl: goUrl('n1-casino'),
  },
  {
    id: 'casino-extra',
    slug: 'casino-extra',
    name: 'Casino Extra',
    shortName: 'CasinoExtra',
    licence: 'Curaçao',
    rating: 6.3,
    ratingLabel: 'Bien',
    bonusAmount: '400 €',
    bonusSuffix: '',
    bonusConditions: 'Wager 30× · dépôt min. 20 €',
    bonusAmountNumber: 400,
    bonusSlug: '400_euros',
    rtp: 95.5,
    paymentMethods: ['VISA', 'MC', 'PAYS'],
    features: ['Fondé 2004', 'Extra Club', 'Wager 30×'],
    pros: [
      'Extra Club : programme de fidélité le plus mature de notre comparatif',
      'Wager 30× — parmi les plus bas',
      "20 ans d'expérience — fiabilité démontrée",
    ],
    cons: ['Design daté (interface 2010s)', 'Pas de crypto', 'Catalogue de jeux moins étoffé'],
    verdict:
      "Casino Extra mise sur l'expérience : 20 ans d'activité, un programme de fidélité bien rodé et les conditions de bonus les plus honnêtes de sa gamme de prix.",
    tagline: "20 ans d'expérience et le programme Extra Club le plus fidèle du marché.",
    logoUrl: LOGO_URLS['casino-extra'],
    affiliateUrl: goUrl('casino-extra'),
  },
  // ── International Big Names ──────────────────────────────────────────────────
  {
    id: 'leovegas',
    slug: 'leovegas',
    name: 'LeoVegas',
    shortName: 'LeoVegas',
    licence: 'MGA (Malte)',
    rating: 8.6,
    ratingLabel: 'Très bien',
    bonusAmount: '1 000 €',
    bonusSuffix: '+ 200 tours',
    bonusConditions: 'Wager 35× · 4 premiers dépôts',
    bonusAmountNumber: 1000,
    bonusSlug: '1000_euros',
    rtp: 96.7,
    paymentMethods: ['VISA', 'MC', 'SKRL', 'PAYS'],
    features: ['Mobile-first', 'Licence MGA', '2 500+ jeux'],
    pros: [
      'Meilleure expérience mobile du marché',
      'Licence MGA — protection maximale',
      'Live casino Evolution Gaming complet',
    ],
    cons: [
      'Wager 35× sur les tours',
      'Accessible depuis la France avec VPN uniquement',
      'Pas de crypto',
    ],
    verdict:
      "LeoVegas est la référence mondiale du casino mobile, récompensé meilleur casino de l'année plusieurs années de suite.",
    tagline: 'La référence mondiale du casino mobile — licence MGA et live Evolution Gaming.',
    logoUrl: LOGO_URLS['leovegas'],
    affiliateUrl: goUrl('leovegas'),
  },
  {
    id: '888-casino',
    slug: '888-casino',
    name: '888 Casino',
    shortName: '888',
    licence: 'MGA / Gibraltar',
    rating: 8.4,
    ratingLabel: 'Très bien',
    bonusAmount: '100 €',
    bonusSuffix: '+ 100 tours',
    bonusConditions: 'Wager 30× · sans code promo',
    bonusAmountNumber: 100,
    bonusSlug: '100_euros',
    rtp: 96.5,
    paymentMethods: ['VISA', 'MC', 'SKRL', 'PAYS', 'PPAL'],
    features: ['Fondé 1997', 'Jeux exclusifs 88', 'Live dealer leader'],
    pros: [
      "25 ans d'histoire — la marque casino la plus connue au monde",
      'Jeux exclusifs développés en interne',
      'PayPal accepté',
    ],
    cons: [
      'Bonus moins généreux en montant',
      'Interface un peu datée',
      'KYC strict dès le premier retrait',
    ],
    verdict:
      '888 Casino est le nom le plus reconnu du gambling en ligne mondial, avec ses propres jeux exclusifs et une fiabilité sans faille depuis 1997.',
    tagline:
      "Plus de 25 ans d'existence — la marque casino en ligne la plus connue et la plus fiable.",
    logoUrl: LOGO_URLS['888-casino'],
    affiliateUrl: goUrl('888-casino'),
  },
  {
    id: 'casumo',
    slug: 'casumo',
    name: 'Casumo',
    licence: 'MGA (Malte)',
    rating: 8.2,
    ratingLabel: 'Très bien',
    bonusAmount: '1 200 €',
    bonusSuffix: '+ 200 tours',
    bonusConditions: 'Wager 30× · 5 premiers dépôts',
    bonusAmountNumber: 1200,
    bonusSlug: '1200_euros',
    rtp: 96.8,
    paymentMethods: ['VISA', 'MC', 'SKRL', 'PAYS'],
    features: ['Gamification unique', 'RTP 96.8%', '2 000+ jeux'],
    pros: [
      'RTP moyen parmi les plus élevés du marché (96.8%)',
      'Système de gamification original avec missions',
      'Pas de barre de chargement — interface ultra-rapide',
    ],
    cons: [
      'Bonus wager élevé (30× peut sembler agressif sur grands montants)',
      'Pas de crypto',
      'Support parfois lent en dehors des heures ouvrées',
    ],
    verdict:
      'Casumo révolutionne le casino en ligne avec sa gamification : chaque session rapporte des points, des aventures et des récompenses uniques.',
    tagline: 'La gamification la plus innovante du marché et le RTP moyen le plus élevé.',
    logoUrl: LOGO_URLS['casumo'],
    affiliateUrl: goUrl('casumo'),
  },
  {
    id: 'mr-green',
    slug: 'mr-green',
    name: 'Mr Green',
    shortName: 'Mr Green',
    licence: 'MGA (Malte)',
    rating: 8.0,
    ratingLabel: 'Très bien',
    bonusAmount: '500 €',
    bonusSuffix: '+ 50 tours',
    bonusConditions: 'Wager 35× · dépôt min. 20 €',
    bonusAmountNumber: 500,
    bonusSlug: '500_euros',
    rtp: 96.5,
    paymentMethods: ['VISA', 'MC', 'SKRL', 'PAYS'],
    features: ['Jeu responsable avancé', 'Licence MGA', '3 000+ jeux'],
    pros: [
      'Meilleurs outils de jeu responsable du marché',
      'Catalogue de plus de 3 000 jeux',
      'Interface moderne et épurée',
    ],
    cons: [
      'Bonus sans tours gratuits sur certains jeux',
      'Pas de crypto',
      'Accessible depuis la France en mode international uniquement',
    ],
    verdict:
      'Mr Green allie le plus grand catalogue du marché aux meilleurs outils de jeu responsable — le choix des joueurs exigeants.',
    tagline: 'Jeu responsable exemplaire et catalogue de 3 000 jeux sous licence MGA.',
    logoUrl: LOGO_URLS['mr-green'],
    affiliateUrl: goUrl('mr-green'),
  },
  {
    id: 'netbet',
    slug: 'netbet',
    name: 'NetBet Casino',
    shortName: 'NetBet',
    licence: 'Curaçao / MGA',
    rating: 7.8,
    ratingLabel: 'Bien',
    bonusAmount: '200 €',
    bonusSuffix: '+ 100 tours',
    bonusConditions: 'Wager 35× · dépôt min. 15 €',
    bonusAmountNumber: 200,
    bonusSlug: '200_euros',
    rtp: 96.2,
    paymentMethods: ['VISA', 'MC', 'SKRL', 'PAYS', 'PPAL'],
    features: ['Double licence', 'Casino + sports', '2 000+ jeux'],
    pros: [
      'Seul opérateur avec licence MGA et accès au marché FR international',
      'Casino et paris sportifs sur la même plateforme',
      'PayPal et Skrill acceptés',
    ],
    cons: [
      'Bonus modeste par rapport à la concurrence',
      'Interface casino moins moderne',
      'Support parfois lent',
    ],
    verdict:
      'NetBet est le pont idéal entre les marchés régulé et offshore — casino, sports et poker sur une même licence MGA.',
    tagline:
      'Double licence MGA + Curaçao — casino, sports et poker réunis sur une seule plateforme.',
    logoUrl: LOGO_URLS['netbet'],
    affiliateUrl: goUrl('netbet'),
  },
  // ── PlayAmo Group (Playamo Partners) ─────────────────────────────────────────
  {
    id: 'playamo',
    slug: 'playamo',
    name: 'PlayAmo',
    licence: 'Curaçao',
    rating: 7.6,
    ratingLabel: 'Bien',
    bonusAmount: '500 €',
    bonusSuffix: '+ 200 tours',
    bonusConditions: 'Wager 40× · 4 premiers dépôts',
    bonusAmountNumber: 500,
    bonusSlug: '500_euros',
    rtp: 96.3,
    paymentMethods: ['VISA', 'MC', '₿', 'ETH', 'LTC'],
    features: ['5 000+ jeux', 'Crypto + fiat', 'Retrait 24h'],
    pros: [
      'Catalogue démesuré : plus de 5 000 jeux',
      'Crypto et méthodes classiques acceptées',
      "Programme VIP avec cashback jusqu'à 20%",
    ],
    cons: [
      'Wager élevé (40×)',
      'Interface parfois surchargée',
      'Support en anglais principalement',
    ],
    verdict:
      'PlayAmo offre le catalogue le plus vaste du marché avec 5 000+ jeux et accepte crypto et fiat — idéal pour explorer de nouveaux titres.',
    tagline: 'Plus de 5 000 jeux, crypto + fiat et programme VIP cashback généreux.',
    logoUrl: LOGO_URLS['playamo'],
    affiliateUrl: goUrl('playamo'),
  },
  {
    id: 'bob-casino',
    slug: 'bob-casino',
    name: 'Bob Casino',
    shortName: 'Bob',
    licence: 'Curaçao / MGA',
    rating: 6.8,
    ratingLabel: 'Bien',
    bonusAmount: '400 €',
    bonusSuffix: '+ 150 tours',
    bonusConditions: 'Wager 40× · 3 premiers dépôts',
    bonusAmountNumber: 400,
    bonusSlug: '400_euros',
    rtp: 95.8,
    paymentMethods: ['VISA', 'MC', '₿', 'ETH', 'SKRL'],
    features: ['Décontracté & fun', '2 500+ jeux', 'Crypto acceptée'],
    pros: [
      'Ambiance décontractée qui tranche avec les casinos classiques',
      'Crypto acceptée en plus des méthodes classiques',
      'Programme de fidélité simple et lisible',
    ],
    cons: [
      'Wager 40× dans la fourchette haute',
      'Moins connu que PlayAmo ou Bitstarz',
      'Support par chat uniquement',
    ],
    verdict:
      'Bob Casino casse les codes avec une interface fun et décontractée, tout en offrant un catalogue solide et la crypto.',
    tagline:
      "L'ambiance fun au service d'un catalogue de 2 500 jeux — casino décontracté et crypto-friendly.",
    logoUrl: LOGO_URLS['bob-casino'],
    affiliateUrl: goUrl('bob-casino'),
  },
  {
    id: 'bizzo-casino',
    slug: 'bizzo-casino',
    name: 'Bizzo Casino',
    shortName: 'Bizzo',
    licence: 'Curaçao / MGA',
    rating: 6.6,
    ratingLabel: 'Bien',
    bonusAmount: '500 €',
    bonusSuffix: '+ 200 tours',
    bonusConditions: 'Wager 40× · 4 premiers dépôts',
    bonusAmountNumber: 500,
    bonusSlug: '500_euros',
    rtp: 96.0,
    paymentMethods: ['VISA', 'MC', '₿', 'ETH', 'LTC'],
    features: ['3 000+ jeux', 'Crypto', 'Playamo Partners'],
    pros: [
      'Double licence Curaçao et MGA',
      'Crypto acceptée sans frais',
      'Catalogue de 3 000+ jeux constamment mis à jour',
    ],
    cons: [
      'Wager 40× — élevé',
      'Marque moins connue que ses concurrents',
      'Pas de version française complète',
    ],
    verdict:
      'Bizzo Casino est la valeur montante du réseau Playamo Partners : double licence, crypto sans frais et catalogue régulièrement enrichi.',
    tagline: 'Double licence et crypto sans frais — la valeur montante du réseau Playamo.',
    logoUrl: LOGO_URLS['bizzo-casino'],
    affiliateUrl: goUrl('bizzo-casino'),
  },
  // ── Bitstarz ─────────────────────────────────────────────────────────────────
  {
    id: 'bitstarz',
    slug: 'bitstarz',
    name: 'BitStarz',
    shortName: 'BitStarz',
    licence: 'Curaçao',
    rating: 7.4,
    ratingLabel: 'Bien',
    bonusAmount: '500 €',
    bonusSuffix: '+ 180 tours',
    bonusConditions: 'Wager 40× · ou 5 BTC · 4 dépôts',
    bonusAmountNumber: 500,
    bonusSlug: '500_euros',
    rtp: 96.6,
    paymentMethods: ['₿', 'ETH', 'LTC', 'DOGE', 'VISA'],
    features: ['Crypto pioneer', '3 600+ jeux', 'Retrait 10 min'],
    pros: [
      'Pionnier du casino crypto depuis 2014 — réputation irréprochable',
      'Retraits en moins de 10 minutes en crypto',
      'Récompensé meilleur casino crypto plusieurs années de suite',
    ],
    cons: [
      'Bonus wager 40× — dans la fourchette haute',
      'Interface crypto-centric — peut dérouter les nouveaux joueurs',
      'Support FR limité',
    ],
    verdict:
      'BitStarz est la référence absolue du casino crypto : fondé en 2014, retraits en 10 minutes et 3 600 jeux — la confiance des puristes.',
    tagline: 'Le pionnier du casino crypto depuis 2014 — retraits en 10 minutes, 3 600 jeux.',
    logoUrl: LOGO_URLS['bitstarz'],
    affiliateUrl: goUrl('bitstarz'),
  },
  // ── National Casino ───────────────────────────────────────────────────────────
  {
    id: 'national-casino',
    slug: 'national-casino',
    name: 'National Casino',
    shortName: 'National',
    licence: 'Curaçao CGA',
    rating: 7.2,
    ratingLabel: 'Bien',
    bonusAmount: '500 €',
    bonusSuffix: '+ 200 tours',
    bonusConditions: 'Wager 35× · dépôt min. 20 €',
    bonusAmountNumber: 500,
    bonusSlug: '500_euros',
    rtp: 96.1,
    paymentMethods: ['VISA', 'MC', '₿', 'ETH', 'PAYS'],
    features: ['5 000+ jeux', 'Nouvelle CGA licence', 'Live Evolution'],
    pros: [
      'Catalogue exceptionnel de plus de 5 000 jeux',
      'Nouvelle licence Curaçao Gaming Authority (CGA) — plus stricte',
      'Live casino Evolution Gaming complet',
    ],
    cons: ['Marque récente — historique court', 'Support parfois débordé', 'Wager 35× standard'],
    verdict:
      'National Casino monte en puissance sur le marché FR : catalogue géant, live Evolution et nouvelle licence CGA plus rigoureuse.',
    tagline: '5 000+ jeux, live Evolution complet et licence CGA — le challenger qui monte.',
    logoUrl: LOGO_URLS['national-casino'],
    affiliateUrl: goUrl('national-casino'),
  },
  // ── VulkanVegas (V.Partners) ──────────────────────────────────────────────────
  {
    id: 'vulkan-vegas',
    slug: 'vulkan-vegas',
    name: 'Vulkan Vegas',
    shortName: 'VulkanVegas',
    licence: 'Curaçao',
    rating: 7.0,
    ratingLabel: 'Bien',
    bonusAmount: '1 000 €',
    bonusSuffix: '+ 125 tours',
    bonusConditions: 'Wager 40× · 2 premiers dépôts',
    bonusAmountNumber: 1000,
    bonusSlug: '1000_euros',
    rtp: 95.9,
    paymentMethods: ['VISA', 'MC', '₿', 'ETH', 'SKRL'],
    features: ['4 000+ jeux', 'Cashback 10%', 'Loot boxes'],
    pros: [
      'Loot boxes hebdomadaires — récompenses aléatoires uniques',
      'Cashback 10% sur les pertes hebdomadaires',
      'Catalogue de plus de 4 000 jeux',
    ],
    cons: ['Wager 40× élevé', 'Design criard — pas au goût de tous', 'Retraits 24-48h'],
    verdict:
      'Vulkan Vegas se distingue par ses loot boxes hebdomadaires et son cashback généreux — une mécanique de récompenses originale.',
    tagline: 'Loot boxes hebdomadaires, cashback 10% et 4 000 jeux — la générosité permanente.',
    logoUrl: LOGO_URLS['vulkan-vegas'],
    affiliateUrl: goUrl('vulkan-vegas'),
  },
  // ── Vavada ────────────────────────────────────────────────────────────────────
  {
    id: 'vavada',
    slug: 'vavada',
    name: 'Vavada Casino',
    shortName: 'Vavada',
    licence: 'Curaçao',
    rating: 6.8,
    ratingLabel: 'Bien',
    bonusAmount: '0 €',
    bonusSuffix: '+ 100 tours sans dépôt',
    bonusConditions: 'Wager 40× · inscription uniquement',
    bonusAmountNumber: 0,
    bonusSlug: 'no_deposit',
    rtp: 96.0,
    paymentMethods: ['VISA', 'MC', '₿', 'ETH', 'USDT'],
    features: ['100 FS sans dépôt', 'RevShare 50%+', '3 000+ jeux'],
    pros: [
      '100 tours gratuits sans dépôt dès inscription',
      'Accepte USDT (Tether) — unique sur le marché',
      'Programme affilié avec les meilleurs taux RevShare',
    ],
    cons: [
      'Bonus sans dépôt wager 40× — restrictif',
      'Marque moins connue en France',
      'Interface traduite approximativement',
    ],
    verdict:
      'Vavada Casino attire par ses 100 tours sans dépôt et son acceptation de USDT — idéal pour tester sans risque financier.',
    tagline: '100 tours gratuits sans dépôt et USDT accepté — testez sans risque.',
    logoUrl: LOGO_URLS['vavada'],
    affiliateUrl: goUrl('vavada'),
  },
  // ── Betsson ────────────────────────────────────────────────────────────────────
  {
    id: 'betsson',
    slug: 'betsson',
    name: 'Betsson',
    licence: 'MGA (Malte)',
    rating: 7.6,
    ratingLabel: 'Bien',
    bonusAmount: '200 €',
    bonusSuffix: '',
    bonusConditions: 'Wager 30× · dépôt min. 20 €',
    bonusAmountNumber: 200,
    bonusSlug: '200_euros',
    rtp: 96.4,
    paymentMethods: ['VISA', 'MC', 'SKRL', 'PAYS', 'PPAL'],
    features: ['Licence MGA', 'Casino + sports', 'Wager 30×'],
    pros: [
      'Présence légale en France pour les paris sportifs',
      'Wager parmi les plus bas du marché (30×)',
      'PayPal et Skrill acceptés — les méthodes les plus sécurisées',
    ],
    cons: [
      'Catalogue casino moins vaste que les spécialistes',
      'Bonus sans tours gratuits',
      'Interface sobre mais peu inspirante',
    ],
    verdict:
      "Betsson apporte la rigueur suédoise à l'iGaming : licence MGA, wager 30× et PayPal — le choix de la sécurité.",
    tagline: 'Licence MGA, wager 30× et PayPal — la rigueur suédoise au service des joueurs FR.',
    logoUrl: LOGO_URLS['betsson'],
    affiliateUrl: goUrl('betsson'),
  },
  // ── Royal Partners brands ─────────────────────────────────────────────────────
  {
    id: 'sol-casino',
    slug: 'sol-casino',
    name: 'Sol Casino',
    shortName: 'Sol',
    licence: 'Curaçao',
    rating: 6.4,
    ratingLabel: 'Bien',
    bonusAmount: '2 000 €',
    bonusSuffix: '+ 200 tours',
    bonusConditions: 'Wager 45× · 4 premiers dépôts',
    bonusAmountNumber: 2000,
    bonusSlug: '2000_euros',
    rtp: 95.5,
    paymentMethods: ['VISA', 'MC', '₿', 'ETH'],
    features: ['Bonus géant 2 000€', 'Thème solaire', '3 500+ jeux'],
    pros: [
      'Package de bienvenue parmi les plus généreux (2 000€)',
      'Thème solaire original et bien exécuté',
      'Crypto acceptée sans frais',
    ],
    cons: ['Wager très élevé (45×)', 'Peu connu en France', 'Support principalement en anglais'],
    verdict:
      'Sol Casino propose le package de bienvenue le plus élevé de notre comparatif — mais les wagers de 45× demandent de la discipline.',
    tagline: 'Le plus gros bonus de bienvenue du marché — 2 000€ pour les nouveaux joueurs.',
    logoUrl: LOGO_URLS['sol-casino'],
    affiliateUrl: goUrl('sol-casino'),
  },
  {
    id: 'jet-casino',
    slug: 'jet-casino',
    name: 'Jet Casino',
    shortName: 'Jet',
    licence: 'Curaçao',
    rating: 6.2,
    ratingLabel: 'Bien',
    bonusAmount: '500 €',
    bonusSuffix: '+ 200 tours',
    bonusConditions: 'Wager 40× · 4 premiers dépôts',
    bonusAmountNumber: 500,
    bonusSlug: '500_euros',
    rtp: 95.3,
    paymentMethods: ['VISA', 'MC', '₿', 'ETH'],
    features: ['Thème aviation', 'Tournois live', '3 000+ jeux'],
    pros: [
      'Tournois live réguliers avec cagnottes',
      'Design aviation original et cohérent',
      'Crypto + fiat acceptés',
    ],
    cons: ['Wager 40× standard', 'Moins établi que les grands noms', 'Support limité en français'],
    verdict:
      'Jet Casino mise sur une identité forte et des tournois live réguliers pour fidéliser sa communauté.',
    tagline:
      'Tournois live réguliers et identité aviation forte — pour les amateurs de compétition.',
    logoUrl: LOGO_URLS['jet-casino'],
    affiliateUrl: goUrl('jet-casino'),
  },
  {
    id: 'fresh-casino',
    slug: 'fresh-casino',
    name: 'Fresh Casino',
    shortName: 'Fresh',
    licence: 'Curaçao',
    rating: 6.0,
    ratingLabel: 'Bien',
    bonusAmount: '500 €',
    bonusSuffix: '+ 200 tours',
    bonusConditions: 'Wager 40× · 4 premiers dépôts',
    bonusAmountNumber: 500,
    bonusSlug: '500_euros',
    rtp: 95.2,
    paymentMethods: ['VISA', 'MC', '₿'],
    features: ['Design frais', 'Cagnotte hebdo', '3 000+ jeux'],
    pros: [
      'Interface fraîche et moderne — design aéré',
      'Cagnottes hebdomadaires pour les joueurs actifs',
      'Catalogue de 3 000 jeux bien sélectionnés',
    ],
    cons: ['Wager 40×', 'Marque récente sans long historique', 'Pas de PayPal'],
    verdict:
      'Fresh Casino séduit par son interface moderne et ses cagnottes hebdomadaires — une entrée fraîche sur le marché.',
    tagline: 'Interface moderne, cagnottes hebdomadaires et 3 000 jeux soigneusement sélectionnés.',
    logoUrl: LOGO_URLS['fresh-casino'],
    affiliateUrl: goUrl('fresh-casino'),
  },
  {
    id: 'rox-casino',
    slug: 'rox-casino',
    name: 'Rox Casino',
    shortName: 'Rox',
    licence: 'Curaçao',
    rating: 5.8,
    ratingLabel: 'Correct',
    bonusAmount: '500 €',
    bonusSuffix: '+ 200 tours',
    bonusConditions: 'Wager 40× · 4 premiers dépôts',
    bonusAmountNumber: 500,
    bonusSlug: '500_euros',
    rtp: 95.0,
    paymentMethods: ['VISA', 'MC', '₿'],
    features: ['Style rock', 'Live casino', '3 000+ jeux'],
    pros: ['Identité rock assumée et cohérente', 'Live casino bien garni', 'Crypto acceptée'],
    cons: [
      'Wager 40× — standard mais élevé',
      'Support FR limité',
      'Moins de promotions que la concurrence',
    ],
    verdict:
      'Rox Casino joue la carte de la différenciation avec son univers rock — une niche qui plaît à sa communauté.',
    tagline:
      "L'identité rock la plus assumée du casino en ligne — pour les joueurs qui sortent des sentiers battus.",
    logoUrl: LOGO_URLS['rox-casino'],
    affiliateUrl: goUrl('rox-casino'),
  },
  {
    id: 'izzi-casino',
    slug: 'izzi-casino',
    name: 'Izzi Casino',
    shortName: 'Izzi',
    licence: 'Curaçao',
    rating: 5.6,
    ratingLabel: 'Correct',
    bonusAmount: '1 500 €',
    bonusSuffix: '+ 150 tours',
    bonusConditions: 'Wager 40× · 4 premiers dépôts',
    bonusAmountNumber: 1500,
    bonusSlug: '1500_euros',
    rtp: 95.1,
    paymentMethods: ['VISA', 'MC', '₿', 'ETH'],
    features: ['Bonus 1 500€', 'Tournois fréquents', '3 000+ jeux'],
    pros: [
      'Package bonus élevé (1 500€)',
      'Tournois de machines à sous fréquents',
      'Crypto acceptée',
    ],
    cons: ['Wager 40× élevé', 'Marque peu connue en France', 'Interface standard sans originalité'],
    verdict:
      'Izzi Casino propose un package bonus solide et des tournois fréquents pour les fans de slots — option honnête sur le segment Curaçao.',
    tagline: '1 500€ de bonus et tournois de slots fréquents pour les amateurs de compétition.',
    logoUrl: LOGO_URLS['izzi-casino'],
    affiliateUrl: goUrl('izzi-casino'),
  },
  // ── N1 Partners brands ────────────────────────────────────────────────────────
  {
    id: 'joo-casino',
    slug: 'joo-casino',
    name: 'Joo Casino',
    shortName: 'Joo',
    licence: 'Curaçao',
    rating: 6.4,
    ratingLabel: 'Bien',
    bonusAmount: '500 €',
    bonusSuffix: '+ 150 tours',
    bonusConditions: 'Wager 40× · dépôt min. 10 €',
    bonusAmountNumber: 500,
    bonusSlug: '500_euros',
    rtp: 96.0,
    paymentMethods: ['VISA', 'MC', '₿', 'ETH', 'SKRL'],
    features: ['N1 Partners', 'Dépôt min. 10€', '2 500+ jeux'],
    pros: [
      'Dépôt minimum très faible (10€)',
      'Réseau N1 Partners — fiabilité éprouvée',
      'Crypto + méthodes classiques',
    ],
    cons: [
      'Wager 40×',
      'Interface peu différenciée des autres marques N1',
      'Support anglophone principalement',
    ],
    verdict:
      "Joo Casino est la porte d'entrée la plus accessible du réseau N1 Partners — dépôt minimum de 10€ et double méthode de paiement.",
    tagline: "Dépôt minimum 10€ et réseau N1 Partners éprouvé — l'accessibilité avant tout.",
    logoUrl: LOGO_URLS['joo-casino'],
    affiliateUrl: goUrl('joo-casino'),
  },
  {
    id: 'slot-hunter',
    slug: 'slot-hunter',
    name: 'Slot Hunter',
    shortName: 'SlotHunter',
    licence: 'Curaçao',
    rating: 6.2,
    ratingLabel: 'Bien',
    bonusAmount: '500 €',
    bonusSuffix: '+ 100 tours',
    bonusConditions: 'Wager 40× · dépôt min. 15 €',
    bonusAmountNumber: 500,
    bonusSlug: '500_euros',
    rtp: 95.9,
    paymentMethods: ['VISA', 'MC', '₿', 'SKRL'],
    features: ['Spécialiste slots', 'Chasse aux bonus', '2 000+ jeux'],
    pros: [
      'Concept original : chasse aux machines à sous rares',
      'Réseau N1 Partners — paiements fiables',
      'Nouvelles sorties mises en avant chaque semaine',
    ],
    cons: ['Catalogue orienté slots — live casino limité', 'Wager 40×', 'Moins de jeux de table'],
    verdict:
      'Slot Hunter est conçu pour les chasseurs de slots : chaque semaine, de nouveaux jeux à débusquer et des promotions dédiées aux machines à sous.',
    tagline:
      'La chasse aux slots la plus fun du marché — nouvelles sorties et promotions dédiées chaque semaine.',
    logoUrl: LOGO_URLS['slot-hunter'],
    affiliateUrl: goUrl('slot-hunter'),
  },
  {
    id: 'fight-club-casino',
    slug: 'fight-club-casino',
    name: 'Fight Club Casino',
    shortName: 'Fight Club',
    licence: 'Curaçao',
    rating: 6.0,
    ratingLabel: 'Bien',
    bonusAmount: '500 €',
    bonusSuffix: '+ 200 tours',
    bonusConditions: 'Wager 40× · dépôt min. 15 €',
    bonusAmountNumber: 500,
    bonusSlug: '500_euros',
    rtp: 95.7,
    paymentMethods: ['VISA', 'MC', '₿', 'ETH'],
    features: ['Thème combat', 'Tournois PvP', '2 000+ jeux'],
    pros: [
      'Tournois PvP entre joueurs — unique sur le marché',
      'Thème combat assumé et cohérent',
      'Crypto acceptée',
    ],
    cons: ['Wager 40×', 'Marque niche — pas pour tous les joueurs', 'Support limité en français'],
    verdict:
      'Fight Club Casino introduit les tournois PvP entre joueurs — un concept unique qui transforme chaque session en compétition.',
    tagline: 'Tournois PvP entre joueurs — le concept de compétition le plus original du marché.',
    logoUrl: LOGO_URLS['fight-club-casino'],
    affiliateUrl: goUrl('fight-club-casino'),
  },
  {
    id: 'n1bet',
    slug: 'n1bet',
    name: 'N1Bet',
    licence: 'Curaçao',
    rating: 5.8,
    ratingLabel: 'Correct',
    bonusAmount: '500 €',
    bonusSuffix: '+ 200 tours',
    bonusConditions: 'Wager 40× · dépôt min. 15 €',
    bonusAmountNumber: 500,
    bonusSlug: '500_euros',
    rtp: 95.6,
    paymentMethods: ['VISA', 'MC', '₿', 'SKRL'],
    features: ['Casino + sports', 'N1 Partners', '2 000+ jeux'],
    pros: [
      'Casino et paris sportifs sur la même plateforme',
      'Réseau N1 Partners — paiements ponctuels',
      'Bonus casino + sports combinables',
    ],
    cons: ['Wager 40×', 'Interface casino et sports peu intégrée', 'Support lent'],
    verdict:
      'N1Bet combine casino et sports betting dans le réseau N1 Partners — pour les joueurs qui veulent tout sur une seule plateforme.',
    tagline: 'Casino et paris sportifs dans le réseau N1 Partners — tout en un.',
    logoUrl: LOGO_URLS['n1bet'],
    affiliateUrl: goUrl('n1bet'),
  },
  // ── MioMedia brands ───────────────────────────────────────────────────────────
  {
    id: 'slots-palace',
    slug: 'slots-palace',
    name: 'SlotsPalace',
    shortName: 'SlotsPalace',
    licence: 'MGA (Malte)',
    rating: 6.6,
    ratingLabel: 'Bien',
    bonusAmount: '500 €',
    bonusSuffix: '+ 100 tours',
    bonusConditions: 'Wager 35× · dépôt min. 20 €',
    bonusAmountNumber: 500,
    bonusSlug: '500_euros',
    rtp: 96.1,
    paymentMethods: ['VISA', 'MC', 'SKRL', 'PAYS'],
    features: ['Licence MGA', 'Spécialiste slots', '2 000+ jeux'],
    pros: [
      'Licence MGA — protection maximale',
      'Wager 35× — dans la fourchette basse pour une MGA',
      'Spécialiste slots avec curation éditoriale',
    ],
    cons: [
      'Pas de crypto',
      'Catalogue moins vaste que les concurrents Curaçao',
      'Peu connu en France',
    ],
    verdict:
      'SlotsPalace est la référence slots sous licence MGA — la fiabilité du cadre maltais pour les amateurs de machines à sous.',
    tagline: 'Licence MGA et curation éditoriale des slots — la fiabilité pour les puristes.',
    logoUrl: LOGO_URLS['slots-palace'],
    affiliateUrl: goUrl('slots-palace'),
  },
  {
    id: 'neon54',
    slug: 'neon54',
    name: 'Neon54',
    licence: 'MGA (Malte)',
    rating: 6.4,
    ratingLabel: 'Bien',
    bonusAmount: '1 000 €',
    bonusSuffix: '+ 200 tours',
    bonusConditions: 'Wager 35× · 4 premiers dépôts',
    bonusAmountNumber: 1000,
    bonusSlug: '1000_euros',
    rtp: 96.0,
    paymentMethods: ['VISA', 'MC', 'SKRL', 'PAYS'],
    features: ['Design néon rétro', 'Licence MGA', '2 000+ jeux'],
    pros: [
      'Design rétro-néon unique et mémorable',
      'Licence MGA sous gestion MioMedia réputée',
      'Package de bienvenue solide (1 000€)',
    ],
    cons: ['Pas de crypto', 'Design très polarisant', 'Support parfois lent'],
    verdict:
      'Neon54 joue la carte du rétro-futurisme avec un design néon assumé et la sécurité de la licence MGA — pour les joueurs qui aiment se démarquer.',
    tagline: 'Design néon rétro unique sous licence MGA — pour ceux qui veulent sortir du lot.',
    logoUrl: LOGO_URLS['neon54'],
    affiliateUrl: goUrl('neon54'),
  },
  // ── Posido ─────────────────────────────────────────────────────────────────────
  {
    id: 'posido',
    slug: 'posido',
    name: 'Posido Casino',
    shortName: 'Posido',
    licence: 'MGA (Malte)',
    rating: 6.8,
    ratingLabel: 'Bien',
    bonusAmount: '2 000 €',
    bonusSuffix: '+ 200 tours',
    bonusConditions: 'Wager 35× · 5 premiers dépôts',
    bonusAmountNumber: 2000,
    bonusSlug: '2000_euros',
    rtp: 96.2,
    paymentMethods: ['VISA', 'MC', 'SKRL', 'PAYS'],
    features: ['Licence MGA', 'Mega bonus 2 000€', 'En forte croissance'],
    pros: [
      'Licence MGA combinée au plus gros bonus de sa catégorie (2 000€)',
      'Conversion FR très élevée — fortement recommandé en 2026',
      'Interface moderne et fluide',
    ],
    cons: ['Marque récente — moins de recul', 'Support en expansion', 'Pas de crypto'],
    verdict:
      'Posido Casino est la grande surprise de 2026 : licence MGA, bonus de 2 000€ et une conversion exceptionnelle sur le marché français.',
    tagline:
      'La grande surprise 2026 — 2 000€ sous licence MGA, taux de conversion FR exceptionnel.',
    logoUrl: LOGO_URLS['posido'],
    affiliateUrl: goUrl('posido'),
  },
  // ── Crypto casinos ────────────────────────────────────────────────────────────
  {
    id: 'mystake',
    slug: 'mystake',
    name: 'MyStake',
    shortName: 'MyStake',
    licence: 'Curaçao CGA',
    rating: 6.6,
    ratingLabel: 'Bien',
    bonusAmount: '1 000 €',
    bonusSuffix: '+ 150 tours',
    bonusConditions: 'Wager 35× · dépôt min. 15 €',
    bonusAmountNumber: 1000,
    bonusSlug: '1000_euros',
    rtp: 96.2,
    paymentMethods: ['VISA', 'MC', '₿', 'ETH', 'USDT'],
    features: ['Mini-jeux originaux', 'Crypto + fiat', '7 000+ jeux'],
    pros: [
      'Catalogue démesuré de plus de 7 000 jeux',
      'Mini-jeux exclusifs (crash, dice, mines) introuvables ailleurs',
      'USDT et crypto sans frais de transaction',
    ],
    cons: [
      'Nouvelle licence CGA — moins de recul réglementaire',
      'Interface dense',
      'Wager 35× standard',
    ],
    verdict:
      'MyStake se démarque par son catalogue de 7 000+ jeux et ses mini-jeux exclusifs — un univers complet pour tous les profils.',
    tagline: '7 000+ jeux dont des mini-jeux exclusifs — le catalogue le plus exhaustif du marché.',
    logoUrl: LOGO_URLS['mystake'],
    affiliateUrl: goUrl('mystake'),
  },
  {
    id: 'bc-game',
    slug: 'bc-game',
    name: 'BC.Game',
    shortName: 'BC.Game',
    licence: 'Curaçao',
    rating: 6.4,
    ratingLabel: 'Bien',
    bonusAmount: '0 €',
    bonusSuffix: '+ bonus quotidiens en crypto',
    bonusConditions: 'Wager variable · selon la crypto',
    bonusAmountNumber: 0,
    bonusSlug: 'crypto_bonus',
    rtp: 97.0,
    paymentMethods: ['₿', 'ETH', 'LTC', 'DOGE', 'USDT'],
    features: ['100% crypto', 'RTP 97%', 'Wheel of Fortune'],
    pros: [
      'RTP exceptionnel de 97% sur les jeux maison',
      'Wheel of Fortune quotidien offrant des crypto gratuites',
      'Accepte plus de 60 cryptomonnaies',
    ],
    cons: [
      'Pas de méthodes de paiement classiques',
      'Interface technique déstabilisante pour les débutants',
      'Bonus crypto complexes à comprendre',
    ],
    verdict:
      'BC.Game est le casino crypto le plus complet du marché : 60+ cryptos acceptées, RTP 97% sur les jeux maison et une roue de la fortune quotidienne.',
    tagline: '60+ cryptos acceptées, RTP 97% et roue de la fortune quotidienne.',
    logoUrl: LOGO_URLS['bc-game'],
    affiliateUrl: goUrl('bc-game'),
  },
  {
    id: 'fortunejack',
    slug: 'fortunejack',
    name: 'FortuneJack',
    shortName: 'FortuneJack',
    licence: 'Curaçao',
    rating: 6.2,
    ratingLabel: 'Bien',
    bonusAmount: '0 €',
    bonusSuffix: '+ 25 tours sans dépôt',
    bonusConditions: 'Wager 40× · crypto uniquement',
    bonusAmountNumber: 0,
    bonusSlug: 'no_deposit',
    rtp: 96.5,
    paymentMethods: ['₿', 'ETH', 'LTC', 'DOGE', 'USDT'],
    features: ['Crypto pioneer 2014', '25 FS sans dépôt', 'RevShare 70%'],
    pros: [
      'Pioneer du gambling crypto depuis 2014',
      '25 tours gratuits sans dépôt pour les nouveaux',
      "Programme affilié avec RevShare jusqu'à 70%",
    ],
    cons: ['Crypto uniquement — pas de fiat', 'Interface technique', 'Support parfois lent'],
    verdict:
      'FortuneJack est un vétéran du casino crypto depuis 2014 : 25 tours sans dépôt, multi-crypto et un des programmes affiliés les plus généreux.',
    tagline: 'Vétéran crypto depuis 2014 — 25 tours sans dépôt et RevShare 70% pour les affiliés.',
    logoUrl: LOGO_URLS['fortunejack'],
    affiliateUrl: goUrl('fortunejack'),
  },
  {
    id: 'rollbit',
    slug: 'rollbit',
    name: 'Rollbit',
    licence: 'Curaçao',
    rating: 6.4,
    ratingLabel: 'Bien',
    bonusAmount: '0 €',
    bonusSuffix: '+ cashback quotidien',
    bonusConditions: 'Wager variable · crypto uniquement',
    bonusAmountNumber: 0,
    bonusSlug: 'cashback',
    rtp: 97.0,
    paymentMethods: ['₿', 'ETH', 'SOL', 'USDT'],
    features: ['Solana accepté', 'NFT intégration', 'RTP 97%'],
    pros: [
      'Solana (SOL) accepté — rare sur le marché',
      'Intégration NFT unique',
      'RTP parmi les plus élevés sur les jeux crash (97%)',
    ],
    cons: [
      'Pas de méthodes de paiement classiques',
      'Interface très orientée crypto/tech — déstabilisante',
      'Marché FR encore peu développé',
    ],
    verdict:
      'Rollbit est à la pointe de la tech crypto : Solana, NFT et RTP 97% — le casino du futur pour les early adopters.',
    tagline: 'Solana, NFT et RTP 97% — le casino crypto le plus technologiquement avancé.',
    logoUrl: LOGO_URLS['rollbit'],
    affiliateUrl: goUrl('rollbit'),
  },
  // ── 22Bet ──────────────────────────────────────────────────────────────────────
  {
    id: '22bet',
    slug: '22bet',
    name: '22Bet',
    licence: 'Curaçao',
    rating: 6.2,
    ratingLabel: 'Bien',
    bonusAmount: '300 €',
    bonusSuffix: '',
    bonusConditions: 'Wager 30× · dépôt min. 15 €',
    bonusAmountNumber: 300,
    bonusSlug: '300_euros',
    rtp: 95.8,
    paymentMethods: ['VISA', 'MC', '₿', 'ETH', 'PAYS'],
    features: ['Casino + sports', 'Wager 30×', '2 500+ jeux'],
    pros: [
      'Wager 30× — parmi les plus bas du marché',
      'Casino et paris sportifs avec les meilleures cotes',
      'Dépôt minimum accessible (15€)',
    ],
    cons: ['Interface peu intuitive', 'Bonus sans tours gratuits', 'Support FR limité'],
    verdict:
      '22Bet offre le wager le plus bas de sa catégorie (30×) avec casino et paris sportifs — le choix du rapport qualité/conditions.',
    tagline: 'Wager 30× parmi les plus bas — casino et sports sur une seule plateforme.',
    logoUrl: LOGO_URLS['22bet'],
    affiliateUrl: goUrl('22bet'),
  },
  // ── Marques françaises classiques ─────────────────────────────────────────────
  {
    id: 'lucky31',
    slug: 'lucky31',
    name: 'Lucky31',
    licence: 'Curaçao',
    rating: 6.4,
    ratingLabel: 'Bien',
    bonusAmount: '400 €',
    bonusSuffix: '+ 200 tours',
    bonusConditions: 'Wager 35× · 4 premiers dépôts',
    bonusAmountNumber: 400,
    bonusSlug: '400_euros',
    rtp: 95.6,
    paymentMethods: ['VISA', 'MC', 'PAYS', 'SKRL'],
    features: ['Interface FR', 'Support FR', '2 000+ jeux'],
    pros: [
      'Interface entièrement en français',
      'Support client francophone dédié',
      'Bonus réparti sur 4 dépôts — accessible',
    ],
    cons: [
      'Catalogue moins vaste que les leaders',
      'Wager 35× standard',
      'Design un peu vieillissant',
    ],
    verdict:
      'Lucky31 est conçu pour les joueurs francophones : interface, support et promotions pensés 100% pour la France.',
    tagline: 'Casino 100% conçu pour les joueurs français — interface, support et promo FR.',
    logoUrl: LOGO_URLS['lucky31'],
    affiliateUrl: goUrl('lucky31'),
  },
  {
    id: 'la-riviera',
    slug: 'la-riviera',
    name: 'La Riviera Casino',
    shortName: 'La Riviera',
    licence: 'Curaçao',
    rating: 6.0,
    ratingLabel: 'Bien',
    bonusAmount: '700 €',
    bonusSuffix: '+ 200 tours',
    bonusConditions: 'Wager 35× · 4 premiers dépôts',
    bonusAmountNumber: 700,
    bonusSlug: '700_euros',
    rtp: 95.4,
    paymentMethods: ['VISA', 'MC', 'PAYS'],
    features: ['Thème luxe FR', 'VIP programme', '1 500+ jeux'],
    pros: [
      'Thème Riviera française luxueux et cohérent',
      'Programme VIP avec avantages exclusifs',
      'Cible explicitement les joueurs français',
    ],
    cons: ['Catalogue limité (1 500 jeux)', 'Pas de crypto', 'Design daté'],
    verdict:
      'La Riviera Casino mise sur le luxe à la française et un programme VIP généreux — pour les joueurs qui apprécient le style.',
    tagline:
      "Le luxe de la Côte d'Azur transposé en ligne — thème français et programme VIP exclusif.",
    logoUrl: LOGO_URLS['la-riviera'],
    affiliateUrl: goUrl('la-riviera'),
  },
  {
    id: 'unique-casino',
    slug: 'unique-casino',
    name: 'Unique Casino',
    shortName: 'Unique',
    licence: 'Curaçao',
    rating: 5.8,
    ratingLabel: 'Correct',
    bonusAmount: '200 €',
    bonusSuffix: '+ 70 tours',
    bonusConditions: 'Wager 40× · dépôt min. 10 €',
    bonusAmountNumber: 200,
    bonusSlug: '200_euros',
    rtp: 95.2,
    paymentMethods: ['VISA', 'MC', 'PAYS', 'SKRL'],
    features: ['Dépôt min. 10€', 'Interface simple', '1 200+ jeux'],
    pros: [
      'Dépôt minimum très faible (10€)',
      'Interface simple et accessible aux débutants',
      'Support en français disponible',
    ],
    cons: ['Catalogue modeste (1 200 jeux)', 'Wager 40× élevé', 'Peu de méthodes crypto'],
    verdict:
      "Unique Casino est la porte d'entrée idéale pour les débutants : dépôt minimum de 10€ et interface épurée sans surcharge.",
    tagline:
      'Dépôt minimum 10€ et interface épurée — le casino des débutants qui veulent commencer simplement.',
    logoUrl: LOGO_URLS['unique-casino'],
    affiliateUrl: goUrl('unique-casino'),
  },
  // ── CBet ──────────────────────────────────────────────────────────────────────
  {
    id: 'cbet',
    slug: 'cbet',
    name: 'CBet Casino',
    shortName: 'CBet',
    licence: 'Curaçao',
    rating: 6.6,
    ratingLabel: 'Bien',
    bonusAmount: '3 000 €',
    bonusSuffix: '+ 300 tours',
    bonusConditions: 'Wager 40× · 5 premiers dépôts',
    bonusAmountNumber: 3000,
    bonusSlug: '3000_euros',
    rtp: 96.0,
    paymentMethods: ['VISA', 'MC', '₿', 'ETH', 'PAYS'],
    features: ['Bonus 3 000€', 'Casino + eSports', '3 000+ jeux'],
    pros: [
      'Package de bienvenue exceptionnel (3 000€ + 300 tours)',
      'Section eSports unique parmi les casinos généralistes',
      'Crypto et fiat acceptés',
    ],
    cons: [
      'Wager 40× élevé — difficile à compléter sur de petits budgets',
      'Interface parfois lente',
      'Support FR limité',
    ],
    verdict:
      'CBet Casino se démarque par le package de bienvenue le plus élevé du marché (3 000€) et sa section eSports unique.',
    tagline:
      '3 000€ de bienvenue et section eSports — le casino avec le plus gros bonus du marché.',
    logoUrl: LOGO_URLS['cbet'],
    affiliateUrl: goUrl('cbet'),
  },
  // ── Goldenbet ─────────────────────────────────────────────────────────────────
  {
    id: 'goldenbet',
    slug: 'goldenbet',
    name: 'Goldenbet',
    licence: 'Curaçao',
    rating: 6.0,
    ratingLabel: 'Bien',
    bonusAmount: '500 €',
    bonusSuffix: '+ 100 tours',
    bonusConditions: 'Wager 35× · dépôt min. 20 €',
    bonusAmountNumber: 500,
    bonusSlug: '500_euros',
    rtp: 95.5,
    paymentMethods: ['VISA', 'MC', '₿', 'PAYS'],
    features: ['Casino + sports', 'Design doré', '2 000+ jeux'],
    pros: ['Casino et paris sportifs intégrés', 'Design premium orienté luxe', 'Crypto acceptée'],
    cons: ['Marque peu connue en France', 'Wager 35×', 'Pas de programme de fidélité clair'],
    verdict:
      'Goldenbet propose un package casino et sports sur un design premium — une alternative sérieuse pour les joueurs multi-produits.',
    tagline:
      'Casino et sports sur une interface premium — or et exclusivité pour les joueurs exigeants.',
    logoUrl: LOGO_URLS['goldenbet'],
    affiliateUrl: goUrl('goldenbet'),
  },
  // ── PIN-UP ─────────────────────────────────────────────────────────────────────
  {
    id: 'pin-up',
    slug: 'pin-up',
    name: 'PIN-UP Casino',
    shortName: 'PIN-UP',
    licence: 'Curaçao',
    rating: 6.2,
    ratingLabel: 'Bien',
    bonusAmount: '500 €',
    bonusSuffix: '+ 250 tours',
    bonusConditions: 'Wager 40× · dépôt min. 10 €',
    bonusAmountNumber: 500,
    bonusSlug: '500_euros',
    rtp: 96.2,
    paymentMethods: ['VISA', 'MC', '₿', 'ETH', 'PAYS'],
    features: ['Design pin-up rétro', '250 tours', '3 000+ jeux'],
    pros: [
      'Design vintage pin-up mémorable et cohérent',
      '250 tours gratuits — parmi les offres les plus généreuses',
      'RTP 96.2% — au-dessus de la moyenne',
    ],
    cons: ['Wager 40× élevé', 'Interface très polarisante', 'Support FR pas toujours disponible'],
    verdict:
      'PIN-UP Casino joue la carte de la nostalgie rétro avec 250 tours gratuits et un RTP au-dessus de la moyenne.',
    tagline: 'Design pin-up vintage, 250 tours gratuits et RTP 96.2% — la nostalgie qui performe.',
    logoUrl: LOGO_URLS['pin-up'],
    affiliateUrl: goUrl('pin-up'),
  },
  // ── Parimatch ─────────────────────────────────────────────────────────────────
  {
    id: 'parimatch',
    slug: 'parimatch',
    name: 'Parimatch',
    shortName: 'Parimatch',
    licence: 'Curaçao',
    rating: 6.0,
    ratingLabel: 'Bien',
    bonusAmount: '150 €',
    bonusSuffix: '',
    bonusConditions: 'Wager 30× · dépôt min. 15 €',
    bonusAmountNumber: 150,
    bonusSlug: '150_euros',
    rtp: 95.8,
    paymentMethods: ['VISA', 'MC', '₿', 'PAYS', 'SKRL'],
    features: ['Casino + sports', 'Wager 30×', 'App mobile dédiée'],
    pros: [
      'Application mobile parmi les mieux notées du marché',
      'Wager 30× — dans les plus favorables',
      'Casino et sports avec les meilleures cotes live',
    ],
    cons: [
      'Bonus plus faible en valeur absolue',
      'Notoriété limitée en France',
      'Interface casino basique',
    ],
    verdict:
      'Parimatch mise sur son application mobile primée et ses cotes sportives compétitives — idéal pour les joueurs hybrides casino/sports.',
    tagline: 'Application mobile primée, wager 30× et cotes sportives compétitives.',
    logoUrl: LOGO_URLS['parimatch'],
    affiliateUrl: goUrl('parimatch'),
  },
  // ── Megapari ──────────────────────────────────────────────────────────────────
  {
    id: 'megapari',
    slug: 'megapari',
    name: 'Megapari',
    licence: 'Curaçao',
    rating: 5.8,
    ratingLabel: 'Correct',
    bonusAmount: '1 750 €',
    bonusSuffix: '+ 290 tours',
    bonusConditions: 'Wager 35× · 4 premiers dépôts',
    bonusAmountNumber: 1750,
    bonusSlug: '1750_euros',
    rtp: 95.9,
    paymentMethods: ['VISA', 'MC', '₿', 'ETH', 'USDT'],
    features: ['Casino + sports + eSports', 'Multi-crypto', '10 000+ jeux'],
    pros: [
      'Catalogue phénoménal : plus de 10 000 jeux',
      'Casino, sports ET eSports sur une seule plateforme',
      'Plus de 50 cryptomonnaies acceptées',
    ],
    cons: [
      'Interface surchargée — navigation difficile',
      'Wager 35× standard',
      'Support FR inégal',
    ],
    verdict:
      'Megapari est la plateforme la plus exhaustive du marché avec 10 000 jeux, sports, eSports et 50+ cryptos — tout pour tout le monde.',
    tagline:
      '10 000+ jeux, sports, eSports et 50 cryptos — la plateforme la plus complète du marché.',
    logoUrl: LOGO_URLS['megapari'],
    affiliateUrl: goUrl('megapari'),
  },
  // ── GG.Bet ────────────────────────────────────────────────────────────────────
  {
    id: 'gg-bet',
    slug: 'gg-bet',
    name: 'GG.Bet',
    shortName: 'GG.Bet',
    licence: 'Curaçao',
    rating: 6.0,
    ratingLabel: 'Bien',
    bonusAmount: '400 €',
    bonusSuffix: '+ 300 tours',
    bonusConditions: 'Wager 40× · dépôt min. 15 €',
    bonusAmountNumber: 400,
    bonusSlug: '400_euros',
    rtp: 96.0,
    paymentMethods: ['VISA', 'MC', '₿', 'ETH', 'SKRL'],
    features: ['Spécialiste eSports', 'Casino + sports', '2 500+ jeux'],
    pros: [
      'Leader mondial des paris eSports (CS2, LoL, Dota2)',
      '300 tours gratuits — offre très généreuse',
      'Casino complet en plus des paris eSports',
    ],
    cons: [
      'Wager 40× élevé',
      'Principalement orienté eSports — peut dérouter les joueurs casino purs',
      'Support FR limité',
    ],
    verdict:
      'GG.Bet est le numéro un mondial des paris eSports avec un casino complet en parallèle — la destination des gamers.',
    tagline: 'N°1 mondial des paris eSports avec 300 tours gratuits — la destination des gamers.',
    logoUrl: LOGO_URLS['gg-bet'],
    affiliateUrl: goUrl('gg-bet'),
  },
  // ── RocketPlay ────────────────────────────────────────────────────────────────
  {
    id: 'rocketplay',
    slug: 'rocketplay',
    name: 'RocketPlay Casino',
    shortName: 'RocketPlay',
    licence: 'Curaçao',
    rating: 5.8,
    ratingLabel: 'Correct',
    bonusAmount: '1 500 €',
    bonusSuffix: '+ 150 tours',
    bonusConditions: 'Wager 40× · 4 premiers dépôts',
    bonusAmountNumber: 1500,
    bonusSlug: '1500_euros',
    rtp: 95.7,
    paymentMethods: ['VISA', 'MC', '₿', 'ETH'],
    features: ['Thème spatial', 'Programme cashback', '3 000+ jeux'],
    pros: [
      'Thème spatial original et bien réalisé',
      'Programme cashback hebdomadaire',
      'Catalogue de 3 000+ jeux en expansion rapide',
    ],
    cons: ['Marque récente — moins de recul', 'Wager 40×', 'Support FR en développement'],
    verdict:
      'RocketPlay Casino décolle avec son thème spatial, son cashback hebdomadaire et un catalogue en expansion rapide.',
    tagline: 'Thème spatial et cashback hebdomadaire — la fusée du casino en ligne qui monte.',
    logoUrl: LOGO_URLS['rocketplay'],
    affiliateUrl: goUrl('rocketplay'),
  },
  // ── Casombie / Oshi / MrBit / Nomad / Casinoly ────────────────────────────────
  {
    id: 'casombie',
    slug: 'casombie',
    name: 'Casombie Casino',
    shortName: 'Casombie',
    licence: 'Curaçao',
    rating: 6.4,
    ratingLabel: 'Bien',
    bonusAmount: '500 €',
    bonusSuffix: '+ 100 tours',
    bonusConditions: 'Wager 35× · dépôt min. 20 €',
    bonusAmountNumber: 500,
    bonusSlug: '500_euros',
    rtp: 96.0,
    paymentMethods: ['VISA', 'MC', '₿', 'ETH', 'PAYS'],
    features: ['Thème zombie', 'Bonus sans restriction', '3 000+ jeux'],
    pros: [
      'Thème zombie original et bien exécuté',
      'Wager 35× — favorable pour sa catégorie',
      'Crypto et fiat sans restrictions',
    ],
    cons: ['Marque de niche', 'Support FR perfectible', 'Peu de promotions récurrentes'],
    verdict:
      'Casombie Casino joue à fond la carte du zombie avec des conditions honnêtes (wager 35×) et un catalogue solide.',
    tagline: 'Thème zombie assumé, wager 35× et crypto/fiat — honnête et décalé.',
    logoUrl: LOGO_URLS['casombie'],
    affiliateUrl: goUrl('casombie'),
  },
  {
    id: 'oshi-casino',
    slug: 'oshi-casino',
    name: 'Oshi Casino',
    shortName: 'Oshi',
    licence: 'Curaçao',
    rating: 6.2,
    ratingLabel: 'Bien',
    bonusAmount: '500 €',
    bonusSuffix: '+ 100 tours',
    bonusConditions: 'Wager 35× · dépôt min. 20 €',
    bonusAmountNumber: 500,
    bonusSlug: '500_euros',
    rtp: 96.3,
    paymentMethods: ['VISA', 'MC', '₿', 'ETH', 'LTC'],
    features: ['Multi-crypto', 'RTP élevé', '2 000+ jeux'],
    pros: [
      'RTP moyen élevé (96.3%) — parmi les meilleurs de sa catégorie',
      'Multi-crypto : BTC, ETH, LTC acceptés',
      'Programme de fidélité par paliers',
    ],
    cons: [
      'Interface sobre sans originalité',
      'Support FR limité',
      'Moins connu que ses concurrents',
    ],
    verdict:
      'Oshi Casino se distingue par son RTP élevé (96.3%) et son acceptation multi-crypto — le bon plan discret du marché.',
    tagline: 'RTP 96.3% et multi-crypto — le bon plan discret pour les joueurs exigeants.',
    logoUrl: LOGO_URLS['oshi-casino'],
    affiliateUrl: goUrl('oshi-casino'),
  },
  {
    id: 'mr-bit',
    slug: 'mr-bit',
    name: 'MrBit Casino',
    shortName: 'MrBit',
    licence: 'Curaçao',
    rating: 6.0,
    ratingLabel: 'Bien',
    bonusAmount: '200 €',
    bonusSuffix: '+ 200 tours',
    bonusConditions: 'Wager 35× · dépôt min. 10 €',
    bonusAmountNumber: 200,
    bonusSlug: '200_euros',
    rtp: 95.8,
    paymentMethods: ['VISA', 'MC', '₿', 'ETH'],
    features: ['200 tours inclus', 'Multi-crypto', '2 500+ jeux'],
    pros: [
      '200 tours gratuits inclus dans le bonus',
      'Dépôt minimum accessible (10€)',
      'Crypto et fiat sans frais',
    ],
    cons: [
      'Bonus modeste en valeur (200€)',
      'Interface standard',
      'Peu de promotions hebdomadaires',
    ],
    verdict:
      'MrBit Casino mise sur les tours gratuits et un dépôt minimum faible — idéal pour tester avec un petit budget.',
    tagline: '200 tours gratuits, dépôt minimum 10€ et crypto — le casino accessible.',
    logoUrl: LOGO_URLS['mr-bit'],
    affiliateUrl: goUrl('mr-bit'),
  },
  {
    id: 'nomad',
    slug: 'nomad',
    name: 'Nomad Casino',
    shortName: 'Nomad',
    licence: 'Curaçao',
    rating: 6.2,
    ratingLabel: 'Bien',
    bonusAmount: '500 €',
    bonusSuffix: '+ 100 tours',
    bonusConditions: 'Wager 35× · dépôt min. 20 €',
    bonusAmountNumber: 500,
    bonusSlug: '500_euros',
    rtp: 96.1,
    paymentMethods: ['VISA', 'MC', '₿', 'ETH', 'PAYS'],
    features: ['Thème nomade', 'RTP 96.1%', '3 000+ jeux'],
    pros: [
      'Thème nomade original — catalogue de jeux du monde entier',
      'RTP 96.1% — au-dessus de la moyenne',
      'Wager 35× favorable',
    ],
    cons: ['Marque récente', 'Support FR en développement', 'Pas de programme de fidélité élaboré'],
    verdict:
      'Nomad Casino se démarque par son thème nomade unique, son RTP au-dessus de la moyenne et un wager favorable.',
    tagline: 'Thème nomade unique, RTP 96.1% et wager 35× — le casino qui voyage bien.',
    logoUrl: LOGO_URLS['nomad'],
    affiliateUrl: goUrl('nomad'),
  },
  {
    id: 'casinoly',
    slug: 'casinoly',
    name: 'Casinoly',
    shortName: 'Casinoly',
    licence: 'MGA (Malte)',
    rating: 6.8,
    ratingLabel: 'Bien',
    bonusAmount: '500 €',
    bonusSuffix: '+ 100 tours',
    bonusConditions: 'Wager 35× · dépôt min. 20 €',
    bonusAmountNumber: 500,
    bonusSlug: '500_euros',
    rtp: 96.2,
    paymentMethods: ['VISA', 'MC', 'SKRL', 'PAYS'],
    features: ['Licence MGA', 'N1 Partners', 'Interface épurée'],
    pros: [
      'Licence MGA dans le réseau N1 Partners — double garantie',
      'Interface la plus épurée et la plus rapide de sa gamme',
      'Wager 35× — favorable pour une MGA',
    ],
    cons: ['Pas de crypto', 'Catalogue moins vaste que Curaçao', 'Peu connu en France'],
    verdict:
      "Casinoly allie la sécurité de la licence MGA à la réactivité du réseau N1 Partners — l'interface la plus fluide de sa catégorie.",
    tagline:
      "Licence MGA, réseau N1 Partners et interface fluide — la combinaison idéale de sécurité et d'expérience.",
    logoUrl: LOGO_URLS['casinoly'],
    affiliateUrl: goUrl('casinoly'),
  },
]

// Sorted by rating descending — default view for all pages
export const TOP_10 = [...operators].sort((a, b) => b.rating - a.rating).slice(0, 10)
export const TOP_3 = TOP_10.slice(0, 3)

// Lookup by slug (O(1) via Map)
export const operatorBySlug = new Map(operators.map((op) => [op.slug, op]))
